import { TaxonomyType } from './index'

export const TAXONOMY_MAP: Record<TaxonomyType, { icon: string; label: string; color: string }> = {
  EMOTIONAL: { icon: 'ph-heart', label: 'Soul', color: 'red' },
  SOUL: { icon: 'ph-heart', label: 'Soul', color: 'red' },
  TIME: { icon: 'ph-hourglass-medium', label: 'Time', color: 'blue' },
  PRESENCE: { icon: 'ph-sparkle', label: 'Presence', color: 'yellow' },
  CREATIVE: { icon: 'ph-palette', label: 'Alchemy', color: 'purple' },
  ALCHEMY: { icon: 'ph-palette', label: 'Alchemy', color: 'purple' },
  SACRIFICIAL: { icon: 'ph-hand-heart', label: 'Offering', color: 'orange' },
  STEADFAST: { icon: 'ph-anchor', label: 'Anchor', color: 'cyan' },
  RADIANT: { icon: 'ph-sun', label: 'Radiant', color: 'orange' },
  WISDOM: { icon: 'ph-brain', label: 'Wisdom', color: 'blue' },
  NURTURING: { icon: 'ph-hand-heart', label: 'Nurturing', color: 'green' },
  ADVENTURE: { icon: 'ph-compass', label: 'Adventure', color: 'purple' },
  GRIT: { icon: 'ph-fire', label: 'Grit', color: 'red' },
  LOYALTY: { icon: 'ph-shield-check', label: 'Loyalty', color: 'blue' },
  CURIOSITY: { icon: 'ph-magnifying-glass', label: 'Curiosity', color: 'yellow' },
  BLISS: { icon: 'ph-butterfly', label: 'Euphor', color: 'pink' },
  COURAGE: { icon: 'ph-shield-chevron', label: 'Courage', color: 'red' },
  HUMILITY: { icon: 'ph-cloud', label: 'Humility', color: 'gray' },
  PATIENCE: { icon: 'ph-hourglass-low', label: 'Patience', color: 'blue' },
  GENEROSITY: { icon: 'ph-gift', label: 'Generosity', color: 'green' },
  INTEGRITY: { icon: 'ph-medal', label: 'Integrity', color: 'gold' },
  PASSION: { icon: 'ph-lightning', label: 'Passion', color: 'red' },
  VITALITY: { icon: 'ph-lightning', label: 'Vitality', color: 'green' },
  UNITY: { icon: 'ph-users-three', label: 'Unity', color: 'purple' },
  FORGIVENESS: { icon: 'ph-dove', label: 'Forgiveness', color: 'white' },
  PLAYFUL: { icon: 'ph-balloon', label: 'Playful', color: 'pink' },
  HEALING: { icon: 'ph-heartbeat', label: 'Healing', color: 'green' },
}

export const TAXONOMY_BACKDROPS: Record<string, string> = {
  EMOTIONAL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1000&auto=format&fit=crop',
  SOUL: 'https://images.unsplash.com/photo-1519750783826-e2420f4d687f?q=80&w=1000&auto=format&fit=crop',
  RADIANT: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?q=80&w=1000&auto=format&fit=crop',
  VITALITY: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000&auto=format&fit=crop',
  BLISS: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop',
  FORGIVENESS: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1000&auto=format&fit=crop',
  HEALING: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1000&auto=format&fit=crop',
  NURTURING: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?q=80&w=1000&auto=format&fit=crop',
  TIME: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?q=80&w=1000&auto=format&fit=crop',
  STEADFAST: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop',
  PATIENCE: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1000&auto=format&fit=crop',
  PRESENCE: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=1000&auto=format&fit=crop',
  UNITY: 'https://images.unsplash.com/photo-1529156069898-49953e39b30f?q=80&w=1000&auto=format&fit=crop',
  PLAYFUL: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1000&auto=format&fit=crop',
  LOYALTY: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=1000&auto=format&fit=crop',
  CURIOSITY: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop',
  CREATIVE: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1000&auto=format&fit=crop',
  ALCHEMY: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?q=80&w=1000&auto=format&fit=crop',
  WISDOM: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=1000&auto=format&fit=crop',
  PASSION: 'https://images.unsplash.com/photo-1557682250-33bd709cbe85?q=80&w=1000&auto=format&fit=crop',
  ADVENTURE: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1000&auto=format&fit=crop',
  SACRIFICIAL: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?q=80&w=1000&auto=format&fit=crop',
  GRIT: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1000&auto=format&fit=crop',
  COURAGE: 'https://images.unsplash.com/photo-1502657877623-f66bf489d236?q=80&w=1000&auto=format&fit=crop',
  INTEGRITY: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=1000&auto=format&fit=crop',
  GENEROSITY: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=1000&auto=format&fit=crop',
  HUMILITY: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=1000&auto=format&fit=crop',
}

export const SPARK_SUGGESTIONS: Partial<Record<TaxonomyType, string[]>> = {
  EMOTIONAL: ["You held space for me when...", "Felt so seen when you...", "Support during the transition..."],
  TIME: ["Grateful for the help with...", "You gave me back my time by...", "Showing up for that hour meant..."],
  PRESENCE: ["Your presence mattered because...", "Just being there meant...", "You showed up when I needed..."],
  CREATIVE: ["Your creativity inspired me...", "You helped me see differently...", "Your artistic eye showed..."],
  SACRIFICIAL: ["You sacrificed for me by...", "What you gave up for me...", "Your generosity with your time..."],
  STEADFAST: ["You stayed steady when...", "I could count on you to...", "Your reliability meant..."],
  RADIANT: ["You lit up the room by...", "Your energy is contagious...", "You make everyone feel..."],
  WISDOM: ["Your advice helped me...", "You guided me to see...", "Your insight was..."],
  NURTURING: ["You took care of me when...", "Your care made me feel...", "You nurtured me by..."],
  ADVENTURE: ["You made life more exciting by...", "You convinced me to try...", "Your adventurous spirit..."],
  GRIT: ["You pushed through when...", "Your determination to...", "You didn't give up when..."],
  LOYALTY: ["I could always count on you to...", "Your loyalty means...", "You've always had my back..."],
  CURIOSITY: ["Your curiosity about...", "You asked questions that made me...", "Your wonder about..."],
  BLISS: ["That moment with you was...", "You bring joy by...", "Pure magic when..."],
  COURAGE: ["You gave me courage by...", "Your bravery inspired...", "You helped me be brave..."],
  HUMILITY: ["You showed humility when...", "Your humility is refreshing...", "You don't seek credit..."],
  PATIENCE: ["You were so patient with me...", "Your patience when I...", "Waiting with you taught me..."],
  GENEROSITY: ["Your generosity with...", "You gave freely when...", "Sharing your..."],
  INTEGRITY: ["You did the right thing by...", "Your integrity shows in...", "I trust you because..."],
  PASSION: ["Your passion for...", "You点燃 my interest in...", "Your enthusiasm for..."],
  VITALITY: ["Your energy is infectious...", "You make life feel alive...", "Your zest for life..."],
  UNITY: ["You brought us together...", "You unite people by...", "Your ability to connect..."],
  FORGIVENESS: ["You forgave me when...", "Your forgiveness means...", "Letting go showed..."],
  PLAYFUL: ["You made me laugh by...", "Your playful spirit...", "Fun moments with you..."],
  HEALING: ["You helped me heal by...", "Your kindness mended...", "You were there when I needed..."],
}
